#!/usr/bin/env bash
# This is a script to install and set up nginx

apt  update
apt install nginx -y


echo "Hello World"  > /var/www/html/index.html

chmod 664 /var/www/html/index.html

service nginx restart

