#!/usr/bin/env bash
# Script print To infinity and beyond
# Sleeps for 2
# print I am invincible when SIGTERM is received

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
