#!/usr/bin/env bash
# Script that print Best School 10 time with while loop
#

i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 8 ]; then
		echo "Best School"
		echo "Hi"

	else
		echo "Best School"
	fi

	((i++))
done
