#!/usr/bin/env bash
# Script that print the content of a the current directory
# in a list format and print numbers and -
#

for file in *; do
	if [ "${file:0:1}" != "." ]; then
		name_part=$(echo "$file" | cut -d '-' -f 2-)

		echo "$name_part"
	fi
done
