#!/usr/bin/env bash
# This script configures Ubuntu server to
# localhost resolves to 127.0.02
# -facebook.com resolves to 8.8.8.8

cp /etc.host ~/hosts.new
echo "127.0.0.2		localhost" >> ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
